views.display_extender.ajax_history:
  type: views_display_extender
  mapping:
    enable_history:
      type: boolean
      label: 'Enable history'
    exclude_args:
      type: text
      label: 'Exclude query arguments from the URL'
